spring.application.name=baozi-store
server.port=8080

# ===== Banco padrao: H2 (permitido pelo enunciado) - arquivo local, dados persistem =====
spring.datasource.url=jdbc:h2:file:./data/baozidb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Console web do H2: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.serialization.write-dates-as-timestamps=false
